#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Tue Jun 02 23:30:25 +08 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# set simulation library paths
xv_cxl_lib_path=""
xv_cpt_lib_path=""
xv_ext_lib_path=""
xv_boost_lib_path="/tools/Xilinx/2025.2/tps/boost_1_72_0"

# compile CPP design sources
echo "xsc -c --gcc_compile_options "-I$xv_boost_lib_path" -work xil_defaultlib -f top_cpp.prj"
xsc -c --gcc_compile_options "-I$xv_boost_lib_path" -work xil_defaultlib -f top_cpp.prj 2>&1 | tee -a compile.log &
XSC_CPP_PID=$!

# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj top_vlog.prj"
xvlog --incr --relax -L uvm -prj top_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
wait $XSC_CPP_PID
echo "No pending jobs, compilation finished."
