#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jun 02 23:30:27 +08 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail

# set simulation library paths
xv_cxl_lib_path=""
xv_cpt_lib_path=""
xv_ext_lib_path=""
xv_boost_lib_path="/tools/Xilinx/2025.2/tps/boost_1_72_0"

# link design libraries
echo "xsc --shared -lib xil_defaultlib -o libdpi.so"
xsc --shared -lib xil_defaultlib -o libdpi.so

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 --include "$xv_boost_lib_path" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.so --snapshot top_behav xil_defaultlib.top xil_defaultlib.glbl -log elaborate.log -dpiheader dpiheader.h"
xelab --incr --debug typical --relax --mt 8 --include "$xv_boost_lib_path" -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.so --snapshot top_behav xil_defaultlib.top xil_defaultlib.glbl -log elaborate.log -dpiheader dpiheader.h

